name: Run BRI Engine 

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python global_bri_master.py
        env:
          # 여기서 GSPREAD_JSON 변수를 전달해줘야 합니다!
          GSPREAD_JSON: ${{ secrets.GSPREAD_JSON }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
